
services:
  app:
    build:
      context: .
      target: app
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data  # Corrected volume mount
    command: uvicorn src.main:app --host 0.0.0.0 --port 3000 --reload
    environment:
      - ENV=development

  test:
    build:
      context: .
      target: test
    depends_on:
      - app
    command: ["pytest", "tests/"]
    environment:
      - ENV=development